#!/bin/bash

# Logo

echo -e "\033[0;34m"
echo "██╗   ██╗ █████╗ ██╗     ██╗ ██████╗  █████╗ ████████╗ ██████╗ ██████╗   ██╗   ██╗███╗   ██╗"
echo "██║   ██║██╔══██╗██║     ██║ ██╔══██╗██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗  ██║   ██║████╗  ██║"
echo "██║   ██║███████║██║     ██║ ██║  ██║███████║   ██║   ██║   ██║██████╔╝  ██║   ██║██╔██╗ ██║"
echo "██║   ██║██╔══██║██║     ██║ ██║  ██║██╔══██║   ██║   ██║   ██║██╔══██╗  ██║   ██║██║╚██╗██║"
echo "╚██████╔╝██║  ██║███████║██║ ██████╔╝██║  ██║   ██║   ╚██████╔╝██║  ██║  ╚██████╔╝██║ ╚████║"
echo " ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝   ╚═════╝ ╚═╝  ╚═══╝"
echo "Services: https://services.validatorvn.com"
echo "Chanel: https://t.me/ValidatorVN"
echo "Github: https://github.com/ValidatorVN"
echo -e "\e[0m"

read -r -p "Enter node name: " NODE_MONIKER

CHAIN_ID="S2-testnet-1"
CHAIN_DENOM="sided"
BINARY_NAME="sided"
GITHUB="https://github.com/ValidatorVN"
BINARY_VERSION_TAG="v0.8.0"

echo -e "Node moniker: ${CYAN}$NODE_MONIKER${NC}"
echo -e "Chain id:     ${CYAN}$CHAIN_ID${NC}"
echo -e "Chain demon:  ${CYAN}$CHAIN_DENOM${NC}"
echo -e "Binary version tag:  ${CYAN}$BINARY_VERSION_TAG${NC}"

sleep 1

echo -e "\e[1m\e[32m1. Updating packages and dependencies--> \e[0m" && sleep 1
#UPDATE APT
sudo apt update && sudo apt upgrade -y
sudo apt install curl tar wget clang pkg-config libssl-dev libleveldb-dev jq build-essential bsdmainutils git make ncdu htop lz4 screen unzip bc fail2ban htop -y

echo -e "\e[1m\e[32m2. Installing GO--> \e[0m" && sleep 1
#INSTALL GO
sudo rm -rf /usr/local/go
curl -L https://go.dev/dl/go1.21.6.linux-amd64.tar.gz | sudo tar -xzf - -C /usr/local
echo 'export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin' >> $HOME/.bash_profile
source .bash_profile

echo -e "\e[1m\e[32m3. Downloading and building binaries--> \e[0m" && sleep 1

cd $HOME
rm -rf side
git clone https://github.com/sideprotocol/side.git
cd side
git checkout v0.8.0
make install

sided config chain-id $CHAIN_ID
sided init "$NODE_MONIKER" --chain-id $CHAIN_ID

wget -O $HOME/.side/config/genesis.json "https://raw.githubusercontent.com/NodeValidatorVN/GuideNode/main/SideProtocol/genesis.json"
wget -O $HOME/.side/config/addrbook.json "https://raw.githubusercontent.com/NodeValidatorVN/GuideNode/main/SideProtocol/addrbook.json"

SEEDS="9c14080752bdfa33f4624f83cd155e2d3976e303@side-testnet-seed.itrocket.net:45656"
PEERS="bbbf623474e377664673bde3256fc35a36ba0df1@side-testnet-peer.itrocket.net:45656,519453a49e25826c04c9d2779ec7b5971876665d@138.201.51.154:32004,59fa36770ef7f6cdbb4fe9c70c13b501c1a6b258@95.214.55.138:4656,a442702f898c77bd1d09ffbbc683946f437c2ac1@209.145.55.218:26656,d5e7f1a7d45b2ad19714d640038cfe8f9f870acc@65.109.80.26:26656,a5fd292715327ca65a8c305fe176166cbe0b8207@146.59.53.93:45656,c41075d4a0f6efc47c3e36a8008a933e603c4313@45.129.147.247:36656,db6fc589d5db96b5ff4e733c16afd4a00488ae96@168.119.10.134:22956,af499b4f78ac7ecf0c340242b973d7592e98db62@213.199.39.54:45656,df3cb7c20c0ca87926a06424a4aebe5cc485301d@54.39.107.180:45656"
sed -i -e "s/^seeds *=.*/seeds = \"$SEEDS\"/; s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $HOME/.side/config/config.toml

sed -i 's|^pruning *=.*|pruning = "custom"|g' $HOME/.side/config/app.toml
sed -i 's|^pruning-keep-recent  *=.*|pruning-keep-recent = "100"|g' $HOME/.side/config/app.toml
sed -i 's|^pruning-interval *=.*|pruning-interval = "10"|g' $HOME/.side/config/app.toml
sed -i 's|^snapshot-interval *=.*|snapshot-interval = 0|g' $HOME/.side/config/app.toml

sed -i 's|minimum-gas-prices =.*|minimum-gas-prices = "0.005uside"|g' $HOME/.side/config/app.toml
sed -i -e "s/prometheus = false/prometheus = true/" $HOME/.side/config/config.toml
sed -i -e "s/^indexer *=.*/indexer = \"null\"/" $HOME/.side/config/config.toml

echo -e "\e[1m\e[32m4. Starting service and synchronization...--> \e[0m" && sleep 1

sudo tee /etc/systemd/system/sided.service > /dev/null <<EOF
[Unit]
Description=Side node
After=network-online.target
[Service]
User=$USER
WorkingDirectory=$HOME/.side
ExecStart=$(which sided) start --home $HOME/.side
Restart=on-failure
RestartSec=5
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable sided

sided tendermint unsafe-reset-all --home ~/.sided/ --keep-addr-book

curl https://snapshot.validatorvn.com/side/data.tar.lz4 | lz4 -dc - | tar -xf - -C $HOME/.sided

sudo systemctl restart sided

echo '=============== SETUP FINISHED ==================='
echo -e "Check logs:            ${CYAN}sudo journalctl -u $BINARY_NAME -f --no-hostname -o cat ${NC}"
echo -e "Check synchronization: ${CYAN}$BINARY_NAME status 2>&1 | jq .SyncInfo.catching_up${NC}"
echo -e "More commands:         ${CYAN}$GITHUB${NC}"
