#!/bin/bash

# Logo

echo -e "\033[0;34m"
echo "██╗   ██╗ █████╗ ██╗     ██╗ ██████╗  █████╗ ████████╗ ██████╗ ██████╗   ██╗   ██╗███╗   ██╗"
echo "██║   ██║██╔══██╗██║     ██║ ██╔══██╗██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗  ██║   ██║████╗  ██║"
echo "██║   ██║███████║██║     ██║ ██║  ██║███████║   ██║   ██║   ██║██████╔╝  ██║   ██║██╔██╗ ██║"
echo "██║   ██║██╔══██║██║     ██║ ██║  ██║██╔══██║   ██║   ██║   ██║██╔══██╗  ██║   ██║██║╚██╗██║"
echo "╚██████╔╝██║  ██║███████║██║ ██████╔╝██║  ██║   ██║   ╚██████╔╝██║  ██║  ╚██████╔╝██║ ╚████║"
echo " ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝   ╚═════╝ ╚═╝  ╚═══╝"
echo "Services: https://services.validatorvn.com"
echo "Chanel: https://t.me/ValidatorVN"
echo "Github: https://github.com/ValidatorVN"
echo -e "\e[0m"

read -r -p "Enter node name: " NODE_MONIKER

CHAIN_ID="zgtendermint_16600-1"
CHAIN_DENOM="0gchaind"
BINARY_NAME="0gchaind"
GITHUB="https://github.com/ValidatorVN"
BINARY_VERSION_TAG="v0.1.0"

echo -e "Node moniker: ${CYAN}$NODE_MONIKER${NC}"
echo -e "Chain id:     ${CYAN}$CHAIN_ID${NC}"
echo -e "Chain demon:  ${CYAN}$CHAIN_DENOM${NC}"
echo -e "Binary version tag:  ${CYAN}$BINARY_VERSION_TAG${NC}"

sleep 1

echo -e "\e[1m\e[32m1. Updating packages and dependencies--> \e[0m" && sleep 1
#UPDATE APT
sudo apt update && sudo apt upgrade -y
sudo apt install curl tar wget clang pkg-config libssl-dev libleveldb-dev jq build-essential bsdmainutils git make ncdu htop lz4 screen unzip bc fail2ban htop -y

echo -e "\e[1m\e[32m2. Installing GO--> \e[0m" && sleep 1
#INSTALL GO
sudo rm -rf /usr/local/go
curl -L https://go.dev/dl/go1.21.6.linux-amd64.tar.gz | sudo tar -xzf - -C /usr/local
echo 'export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin' >> $HOME/.bash_profile
source .bash_profile

echo -e "\e[1m\e[32m3. Downloading and building binaries--> \e[0m" && sleep 1

git clone -b v0.1.0 https://github.com/0glabs/0g-chain.git
./0g-chain/networks/testnet/install.sh
source .profile

0gchaind config chain-id $CHAIN_ID
0gchaind init "$NODE_MONIKER" --chain-id $CHAIN_ID

wget -O $HOME/.0gchain/config/genesis.json "https://raw.githubusercontent.com/NodeValidatorVN/GuideNode/main/0G/genesis.json"
wget -O $HOME/.0gchain/config/addrbook.json "https://raw.githubusercontent.com/NodeValidatorVN/GuideNode/main/0G/addrbook.json"

sed -i -e 's|^seeds *=.*|seeds = ""|' $HOME/.0gchain/config/config.toml
sed -i -e 's|^persistent_peers *=.*|persistent_peers = "f878d40c538c8c23653a5b70f615f8dccec6fb9f@54.215.187.94:26656,9d88e34a436ec1b50155175bc6eba89e7a1f0e9a@213.199.61.18:2665"|' $HOME/.0gchain/config/config.toml

sed -i 's|^pruning *=.*|pruning = "custom"|g' $HOME/.0gchain/config/app.toml
sed -i 's|^pruning-keep-recent  *=.*|pruning-keep-recent = "100"|g' $HOME/.0gchain/config/app.toml
sed -i 's|^pruning-interval *=.*|pruning-interval = "10"|g' $HOME/.0gchain/config/app.toml
sed -i 's|^snapshot-interval *=.*|snapshot-interval = 0|g' $HOME/.0gchain/config/app.toml

sed -i 's|^minimum-gas-prices *=.*|minimum-gas-prices = "0.025ua0gi"|g' $HOME/.0gchain/config/app.toml
sed -i 's|^prometheus *=.*|prometheus = true|' $HOME/.0gchain/config/config.toml

echo -e "\e[1m\e[32m4. Starting service and synchronization...--> \e[0m" && sleep 1

cp $HOME/go/bin/0gchaind /usr/local/bin
chmod +x /usr/local/bin/0gchaind

sudo tee /etc/systemd/system/0gchaind.service > /dev/null << EOF
[Unit]
Description=0G node service
After=network-online.target
[Service]
User=$USER
ExecStart=/usr/local/bin/0gchaind start --home $HOME/.0gchain
Restart=on-failure
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF
sudo systemctl daemon-reload
sudo systemctl enable 0gchaind.service

0gchaind tendermint unsafe-reset-all --home $HOME/.0gchain --keep-addr-book

curl https://snapshot.validatorvn.com/og/data.tar.lz4 | lz4 -dc - | tar -xf - -C $HOME/.0gchain

sudo systemctl start 0gchaind

echo '=============== SETUP FINISHED ==================='
echo -e "Check logs:            ${CYAN}sudo journalctl -u $BINARY_NAME -f --no-hostname -o cat ${NC}"
echo -e "Check synchronization: ${CYAN}$BINARY_NAME status 2>&1 | jq .SyncInfo.catching_up${NC}"
echo -e "More commands:         ${CYAN}$GITHUB${NC}"
